//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1beta1

import (
	"github.com/crossplane/crossplane-runtime/v2/apis/common"
	"k8s.io/api/core/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Delims) DeepCopyInto(out *Delims) {
	*out = *in
	if in.Left != nil {
		in, out := &in.Left, &out.Left
		*out = new(string)
		**out = **in
	}
	if in.Right != nil {
		in, out := &in.Right, &out.Right
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Delims.
func (in *Delims) DeepCopy() *Delims {
	if in == nil {
		return nil
	}
	out := new(Delims)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GenerateTokenRequest) DeepCopyInto(out *GenerateTokenRequest) {
	*out = *in
	in.UsernameSecretRef.DeepCopyInto(&out.UsernameSecretRef)
	in.PasswordSecretRef.DeepCopyInto(&out.PasswordSecretRef)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GenerateTokenRequest.
func (in *GenerateTokenRequest) DeepCopy() *GenerateTokenRequest {
	if in == nil {
		return nil
	}
	out := new(GenerateTokenRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Input) DeepCopyInto(out *Input) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	if in.Delims != nil {
		in, out := &in.Delims, &out.Delims
		*out = new(Delims)
		(*in).DeepCopyInto(*out)
	}
	if in.RancherSecretRef != nil {
		in, out := &in.RancherSecretRef, &out.RancherSecretRef
		*out = new(v1.SecretKeySelector)
		(*in).DeepCopyInto(*out)
	}
	if in.ImportProjects != nil {
		in, out := &in.ImportProjects, &out.ImportProjects
		*out = make([]*ProjectRequest, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(ProjectRequest)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	if in.GenerateRancherProviderCredentials != nil {
		in, out := &in.GenerateRancherProviderCredentials, &out.GenerateRancherProviderCredentials
		*out = make([]*ProviderCredentialRequest, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(ProviderCredentialRequest)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	if in.GenerateTokens != nil {
		in, out := &in.GenerateTokens, &out.GenerateTokens
		*out = make([]*GenerateTokenRequest, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(GenerateTokenRequest)
				(*in).DeepCopyInto(*out)
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Input.
func (in *Input) DeepCopy() *Input {
	if in == nil {
		return nil
	}
	out := new(Input)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Input) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProjectRequest) DeepCopyInto(out *ProjectRequest) {
	*out = *in
	if in.ProviderConfigReference != nil {
		in, out := &in.ProviderConfigReference, &out.ProviderConfigReference
		*out = new(common.ProviderConfigReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProjectRequest.
func (in *ProjectRequest) DeepCopy() *ProjectRequest {
	if in == nil {
		return nil
	}
	out := new(ProjectRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProviderCredentialRequest) DeepCopyInto(out *ProviderCredentialRequest) {
	*out = *in
	in.UsernameSecretRef.DeepCopyInto(&out.UsernameSecretRef)
	in.PasswordSecretRef.DeepCopyInto(&out.PasswordSecretRef)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProviderCredentialRequest.
func (in *ProviderCredentialRequest) DeepCopy() *ProviderCredentialRequest {
	if in == nil {
		return nil
	}
	out := new(ProviderCredentialRequest)
	in.DeepCopyInto(out)
	return out
}
